version: '2'
services:
  rdf4j:
    environment:
      - APP_LOGGING_LEVEL=DEBUG
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:5555:5555
    build: .
    restart: always
    volumes:
      - rdf4j_data:/var/rdf4j
      - rdf4j_logs:/usr/local/tomcat/logs
    networks:
      - rdf4j-fuseki-net
  fuseki:
    image: fuseki:latest
    container_name: fuseki
    environment:
      - FUSEKI_USE_REF_CONFIG_TDB2=1
    ports:
      - 127.0.0.1:3030:3030
    networks:
      - rdf4j-fuseki-net
volumes:
  rdf4j_data:
  rdf4j_logs:

networks:
  rdf4j-fuseki-net:
